### ISSUE TITLE
Tkinter not working

### ISSUE THREAD

**Issue by XenonPy** [glotcode/glot#46]

**Comment by Kouroshdan** [comment]
please provid some discription.
is there any errors ?

**Comment by XenonPy** [comment]
`import tkinter`: Traceback (most recent call last):
  File "/home/glot/main.py", line 1, in <module>
    import tkinter
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
